version: '3'

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=komo
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
